array_width = 60
attr_fn_like_width = 80
binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 0
brace_style = "SameLineWhere"
chain_width = 80
color = "Auto"
combine_control_expr = true
comment_width = 80
condense_wildcard_suffixes = false
control_brace_style = "AlwaysSameLine"
edition = "2024"
empty_item_single_line = true
enum_discrim_align_threshold = 40
error_on_line_overflow = true
error_on_unformatted = true
fn_call_width = 80
fn_params_layout = "Compressed"
fn_single_line = true
force_explicit_abi = true
force_multiline_blocks = false
format_code_in_doc_comments = true
doc_comment_code_block_width = 100
format_generated_files = true
format_macro_matchers = true
format_macro_bodies = true
skip_macro_invocations = []
format_strings = true
hard_tabs = false
hex_literal_case = "Upper"
show_parse_errors = true
ignore = []
imports_indent = "Block"
imports_layout = "HorizontalVertical"
indent_style = "Block"
inline_attribute_width = 0
match_arm_blocks = true
match_arm_leading_pipes = "Never"
match_block_trailing_comma = false
max_width = 100
merge_derives = true
imports_granularity = "Crate"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_modules = true
required_version = "1.8.0"
short_array_element_width_threshold = 20
skip_children = true
single_line_if_else_max_width = 80
single_line_let_else_max_width = 80
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_field_align_threshold = 20
struct_lit_single_line = true
struct_lit_width = 60
struct_variant_width = 60
style_edition = "2024"
tab_spaces = 4
trailing_comma = "Always"
trailing_semicolon = true
type_punctuation_density = "Wide"
use_field_init_shorthand = true
use_small_heuristics = "Default"
use_try_shorthand = true
where_single_line = true
wrap_comments = true